---
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: quarterly
      time: "12:00"
      timezone: America/Los_Angeles
    groups:
      submodules:
        patterns:
          - "*"
    assignees:
      - grayespinoza
    commit-message:
      prefix: chore
